Provided Types virtualization
auduchinok/fsharp pull request #2
Opened 2020-06-19 17:02 UTC by DedSec256

2020-07-20 13:00 UTC, auduchinok commented on tests/service/EditorTests.fs
> +    let item = decls.Items |> Seq.tryFind (fun d -> d.Name = "abc")
Is it related to the type providers somehow?

2020-07-20 13:28 UTC, DedSec256 commented on tests/service/EditorTests.fs
> +    let item = decls.Items |> Seq.tryFind (fun d -> d.Name = "abc")
no and it's fixed in https://github.com/auduchinok/visualfsharp/pull/4

2021-02-10 11:42 UTC, auduchinok requested changes
Would it be possible to reduce the diff? We'll have to maintain the changes every time we update FCS, so we need to prevent changes that aren't needed.

2021-02-10 11:42 UTC, auduchinok commented on src/fsharp/ExtensionTyping.fsi
> +open System.Reflection
Why it's not near other opens?

2021-02-10 11:42 UTC, auduchinok commented on src/fsharp/ExtensionTyping.fsi
> -    open System.IO
Do we really need this change?

2021-02-10 11:42 UTC, auduchinok commented on src/fsharp/ExtensionTyping.fs
> -    let GetTypeProvidersOfAssembly
Is it necessary to remove it and not just call it below?

2021-03-11 13:12 UTC, merged